---
- name: Executing Show ARP on IOS Mgmt VRF
  hosts: router1.local
  gather_facts: no
  vars:
     ansible_user: admin
     ansible_ssh_pass: admin
  tasks:
  - raw: "show arp vrf mgmt-intf"
    changed_when: False

- name: Executing Show ARP on NxOS Mgmt VRF
  hosts: nxswitch1.local
  gather_facts: no
  vars:
     ansible_user: admin
     ansible_ssh_pass: admin
  tasks:
  - raw: "show ip arp vrf management"
    changed_when: False

- name: Executing Show running-config
  hosts: eos
  gather_facts: no
  vars:
     ansible_user: admin
     ansible_ssh_pass: admin
  tasks:
  - raw: "show running-config"
    changed_when: False
