---
- name: EOS Show Commands
  hosts: eos
  gather_facts: false

  tasks:
    - name: Backup current switch config (eos)
      eos_config:
        backup: yes
      register: output
      when: ansible_network_os == 'eos'

    - name: show output
      debug:
        var: output

    - name: eos show version
      eos_command:
        commands:
          - show version
      register: output1

    - name: show output
      debug:
        var: output1

