---
- name: Deleting Multiple VRF's
  hosts: eos
  gather_facts: false

  tasks:
    - name: Delete aggregate of VRFs
      eos_vrf:
        aggregate:
          - name: achme1
          - name: achme2
        state: absent
