---
- name: EOS deletion of VLANs
  hosts: eos
  gather_facts: false

  tasks:
    - name: deleting Vlans
      eos_vlan:
        vlan_id: "{{item.id}}"
        state:   "{{item.state | default('absent') }}"
      with_items: "{{vlans}}"
    - name: show available vlans
      eos_command:
        commands: show vlan
      register: result
    - debug: var=result.stdout_lines

