---

loopback: 10.255.0.4/32

bgp_fabric:
  asn: 65002
  router_id: 10.255.0.4
  neighbor:
    - {address: 172.16.3.2, remote_as: 65000}
    - {address: 172.16.6.2, remote_as: 65000}
    - {address: 172.16.10.2, remote_as: 65005}
  networks:
    - 10.255.0.4/32
    - 172.16.3.0/24
    - 172.16.6.0/24
    - 172.16.10.0/24
    - 10.0.101.0/24

spanning_tree:
  mode: mstp
  disabled_vlans: 4094

mlag:
  domain_id: mlag-10
  local_interface: Vlan4094
  peer_address: 169.254.1.2
  primary_priority: 20
  peer_link: Ethernet4

vlans:
  4094:
    alias: peerlink-vlan
    pipv4: 169.254.1.1/30
    trunk_group: mlagpeer
    options: no autostate
  101:
    alias: prod-server-101
    vipv4: 10.0.101.254
    pipv4: 10.0.101.253/24

virtual_router_mac_address: 00:1c:73:00:00:99

interfaces:
  Ethernet1:
    alias: uplink-spine-1
    port_state: no switchport
    address: 172.16.3.1/24
  Ethernet2:
    alias: uplink-spine-2
    port_state: no switchport
    address: 172.16.6.1/24
  Ethernet4:
    alias: peerlink-leaf-1
    port_state: switchport mode trunk
    switchport_trunk: group mlagpeer
