---

loopback: 10.255.0.1/32

bgp_fabric:
  asn: 65000
  router_id: 10.255.0.1
  neighbor:
    - {address: 172.16.1.1, remote_as: 65001}
    - {address: 172.16.3.1, remote_as: 65002}
    - {address: 172.16.4.1, remote_as: 65003}
    - {address: 172.16.5.1, remote_as: 65004}
  networks:
    - 10.255.0.1/32
    - 172.16.1.0/24
    - 172.16.3.0/24
    - 172.16.4.0/24
    - 172.16.5.0/24

interfaces:
  Ethernet1:
    alias: downlink-leaf-1
    port_state: no switchport
    address: 172.16.1.2/24
  Ethernet2:
    alias: downlink-leaf-2
    port_state: no switchport
    address: 172.16.3.2/24
  Ethernet3:
    alias: downlink-leaf-3
    port_state: no switchport
    address: 172.16.4.2/24
  Ethernet4:
    alias: downlink-leaf-4
    port_state: no switchport
    address: 172.16.5.2/24
