---
- hosts: ios
  gather_facts: no
  connection: local

  vars:
    iosv_var:
         host: "{{ inventory_hostname }}"    # if multiple hosts are their in routers then "{{ inventory_hostname }}"
         username: cisco
         password: cisco
         transport: cli

  tasks:
    - name: load new acl into device
      ios_config:
        lines:
          -  10 permit ip host 1.1.1.1 any log
          -  20 permit ip host 2.2.2.2 any log
          -  30 permit ip host 3.3.3.3 any log
          -  40 permit ip host 4.4.4.4 any log
          -  50 permit ip host 5.5.5.5 any log
        parents: ip access-list extended test
        before: no ip access-list extended test
        match: exact                           # if match filed is not included then it will consider it as match=none it will not do any check
        provider: "{{ iosv_var }}"
    - name: Adding routing protocol RIP
      ios_config:
        lines:
          - router rip
          - version 2
          - network 191.168.0.0
        parents: version 2
        match: exact
        provider: "{{ iosv_var }}"
