---
- hosts: ios
  gather_facts: no
  connection: local

  vars:
    iosv_var:
        host: "{{ inventory_hostname }}"   
        username: admin
        password: admin

  tasks:
    - name: getting complete information of device
      ios_command:
         provider: "{{ iosv_var }}"
         commands: sh run
      register: result1
    - debug: var=result1
    - name: getting complete information of device
      ios_command:
         provider: "{{ iosv_var }}"
         commands:
             - show ip interface brief
             - show ip route
      register: result1
    - debug: var=result1

