---
- hosts: nxos
  gather_facts: no
  connection: local

  vars:
    nxos_var:
      host: "{{ inventory_hostname }}"   
      username: admin
      password: admin
#      transport: cli
  tasks:
    - name: load new acl into device
      ios_config:
        lines:
          -  10 permit ip host 1.1.1.1 any log
        parents: ip access-list extended test
        before: no ip access-list extended test
        match: exact                  
        provider: "{{ nxos_var }}"
