---
vlans:
  - { id: "1", name: "default" }
  - { id: "100", name: "mgmt", subnet: "172.16.2.0/24"}
  - { id: "101", name: "web",  subnet: "192.168.201.0/24"}
  - { id: "110", name: "db",   subnet: "192.168.202.0/24"}

vrfs:
  - { name: achme1, rd: "1:204" }
  - { name: achme2, rd: "1:205" }
