ansible_connection: network_cli
ansible_network_os: eos
ansible_user: admin
ansible_ssh_pass: admin
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: admin
#ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion01"'

