#!/usr/bin/env python

import sys
import os
import yaml
import json

def convert(filename):
    with open(filename) as temp:
        return yaml.load(temp)

with open(sys.argv[1]) as temp:
   Input = temp.read()
Output = yaml.load(Input);

os.system('clear')

print('**********YAML************')
print Input

print('\n**********PYTHON************')
print Output

print('\n**********JSON*************')
print json.dumps(Output, sort_keys=True, indent=2, separators=(', ', ': '))
