#!/usr/bin/env python

import sys
import os
import yaml

def convert(filename):
    with open(filename) as temp:
        return yaml.load(temp)

os.system('clear')

with open(sys.argv[1]) as temp:
   Input = temp.read()

print('********YAML*****************')
print Input

Output = convert(sys.argv[1]);
print('**********PYTHON***************')
print Output
print type(Output)
